# System and Experiment
experiment = "TransUNet_baseline"
seed = 42
num_workers = 4

# Data Configuration
datasets = ["bone_tooth_mask", "bone_tooth_mask_1209"]
split_filename = "dataset_1209"
num_folds = 4
batch_size = 16

# Training Settings
num_epochs = 50

# Model Architecture
[model]
name = "TransUNet"

[model.parameters]
in_channels = 1
num_classes = 3

# Optimizer
[optimizer]
name = "Adam"

[optimizer.parameters]
lr = 1e-4

# Loss Function
[loss]
name = "MultipleLoss"
main_loss = "Total Loss"

[loss.parameters]
num_classes = 3

# Metric
[metric]
name = "mIoU"

[metric.parameters]
num_classes = 3
class_names = ["Tooth", "Bone"]
monitor = "IoU (Tooth)"
